var androids =
    [{"key":"B00OSTKZWM",
    "name":"Ract-JS",
    "price":57.99},
    {"key":"B00OSTKZW1",
    "name":"Angular-JS",
    "price":65.99},
    {"key":"B00OSTKZW2",
    "name":"Vue-JS",
    "price":88.99},
    {"key":"B00OSTKZ3",
    "name":"Biggener-JS",
    "price":98.99},
    {"key":"B00OSTKZW4",
    "name":"Advance Ract-JS",
    "price":75.99},
    {"key":"B00OSTKZW5",
    "name":"Advance Angular-JS",
    "price":90.99},
    {"key":"B00OSTKZW6",
    "name":"Advance-Vue-JS",
    "price":57.99},
    {"key":"B00OSTKZW7",
    "name":"Ract-JS-biggener",
    "price":50.99},
    {"key":"B00OSTKZW8",
    "name":"Full-stack-Dev",
    "price":157.99},
    {"key":"B00OSTKZWM9",
    "name":"OOPs Concept",
    "price":90.99},
    {"key":"B00OSTKZWM10",
    "name":"Java Script",
    "price":87.99},
    {"key":"B00OSTKZWM11",
    "name":"Advance Java Script",
    "price":90.99}
    ];

export default androids;